add_lunch_combo tp_grouper-userdebug
add_lunch_combo tp_vibrantmtd-userdebug
add_lunch_combo tp_galaxysmtd-userdebug
add_lunch_combo tp_maguro-userdebug
add_lunch_combo tp_hercules-userdebug
add_lunch_combo tp_skyrocket-userdebug
add_lunch_combo tp_n7000-userdebug
